### ISSUE TITLE
Invalid appsecret_proof

### ISSUE THREAD

**Issue by ilyagtangelogamescom** [restfb/restfb#1118]
Hi, from 100% of requests ~5-10% I'm getting an error  `com.restfb.exception.FacebookGraphException: Received Facebook error response of type GraphMethodException: Invalid appsecret_proof provided in the API argument (code 100,$
        at com.restfb.exception.generator.DefaultFacebookExceptionGenerator$DefaultGraphFacebookExceptionMapper.exceptionForTypeAndMessage(DefaultFacebookExceptionGenerato$
        at com.restfb.exception.generator.DefaultFacebookExceptionGenerator.throwFacebookResponseStatusExceptionIfNecessary(DefaultFacebookExceptionGenerator.java:61) ~[re$
        at com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:793) ~[restfb-3.6.1.jar:?]`

I've checked several times app secret and app id. All flow is according to the documentation. Could you please help me and explain what I'm missing?

**Comment by nbartels** [comment]
Can you elaborate on what kind of requests this happens?

**Comment by ilyagtangelogamescom** [comment]
When I'm trying to fetch customer data
