### ISSUE TITLE
How to obtain information of another user

### ISSUE THREAD

**Issue by MrFirekiller** [restfb/restfb#1190]
Here is my code:

```java
package main;

import com.restfb.DefaultFacebookClient;
import com.restfb.FacebookClient;
import com.restfb.Version;
import com.restfb.types.User;

public class SocialMediaSearch {
	
	private static final String accessToken = "Token";
	private static final FacebookClient client = new DefaultFacebookClient(accessToken, Version.LATEST);
	
	public static void main(String[] args) {
	    String result = client.fetchObject("Joe Biden", User.class).getName();
	    System.out.println(result);

	}
	
}
```

It creates this exception:

```java
Exception in thread "main" com.restfb.exception.FacebookJsonMappingException: Unable to map JSON to Java. Offending JSON is '<!DOCTYPE html>
<html lang="en" id="facebook">
  <head>
    <title>Facebook | Error</title>
    <meta charset="utf-8">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="cache-control" content="no-store">
    <meta http-equiv="cache-control" content="max-age=0">
    <meta http-equiv="expires" content="-1">
    <meta http-equiv="pragma" content="no-cache">
    <meta name="robots" content="noindex,nofollow">
    <style>
      html, body {
        color: #141823;
        background-color: #e9eaed;
        font-family: Helvetica, Lucida Grande, Arial,
                     Tahoma, Verdana, sans-serif;
        margin: 0;
        padding: 0;
        text-align: center;
      }

      #header {
        height: 30px;
        padding-bottom: 10px;
        padding-top: 10px;
        text-align: center;
      }

      #icon {
        width: 30px;
      }

      h1 {
        font-size: 18px;
      }

      p {
        font-size: 13px;
      }

      #footer {
        border-top: 1px solid #ddd;
        color: #9197a3;
        font-size: 12px;
        padding: 5px 8px 6px 0;
      }
    </style>
  </head>
  <body>
    <div id="header">
      <a href="//www.facebook.com/">
        <img id="icon" src="//static.facebook.com/images/logos/facebook_2x.png" />
      </a>
    </div>
    <div id="core">
      <h1 id="sorry">Sorry, something went wrong.</h1>
      <p id="promise">
        We're working on it and we'll get it fixed as soon as we can.
      </p>
      <p id="back-link">
        <a id="back" href="//www.facebook.com/">Go Back</a>
      </p>
      <div id="footer">
        Facebook
        <span id="copyright">
          &copy; 2021
        </span>
        <span id="help-link">
          &#183;
          <a id="help" href="//www.facebook.com/help/">Help Center</a>
        </span>
      </div>
    </div>
    <script>
      document.getElementById('back').onclick = function() {
        if (history.length > 1) {
          history.back();
          return false;
        }
      };

      // Adjust the display based on the window size
      if (window.innerHeight < 80 || window.innerWidth < 80) {
        // Blank if window is too small
        document.body.style.display = 'none';
      };
      if (window.innerWidth < 200 || window.innerHeight < 150) {
        document.getElementById('back-link').style.display = 'none';
        document.getElementById('help-link').style.display = 'none';
      };
      if (window.innerWidth < 200) {
        document.getElementById('sorry').style.fontSize = '16px';
      };
      if (window.innerWidth < 150) {
        document.getElementById('promise').style.display = 'none';
      };
      if (window.innerHeight < 150) {
        document.getElementById('sorry').style.margin = '4px 0 0 0';
        document.getElementById('sorry').style.fontSize = '14px';
        document.getElementById('promise').style.display = 'none';
      };
    </script>
  </body>
</html>'.
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:248)
	at com.restfb.DefaultFacebookClient.fetchObject(DefaultFacebookClient.java:293)
	at main.SocialMediaSearch.main(SocialMediaSearch.java:15)
Caused by: com.restfb.json.ParseException: Expected value at 1:1
	at com.restfb.json.JsonParser.error(JsonParser.java:488)
	at com.restfb.json.JsonParser.expected(JsonParser.java:484)
	at com.restfb.json.JsonParser.readValue(JsonParser.java:188)
	at com.restfb.json.JsonParser.parse(JsonParser.java:147)
	at com.restfb.json.JsonParser.parse(JsonParser.java:88)
	at com.restfb.json.Json.parse(Json.java:275)
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:209)
	... 2 more
```

I think that the problem has something to do with the "Caused by:... Expected value at 1:1" but I am not sure what to do. How can I solve this?

**Comment by nbartels** [comment]
You cannot use a name to fetch a user. You need an ID or the username. The username must not contain a space.
Despite from that, the code looks okay.

**Comment by MrFirekiller** [comment]
So I fixed that and now it throws this:
```java
Exception in thread "main" com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: (#10) This endpoint requires the 'pages_read_engagement' permission or the 'Page Public Content Access' feature or the 'Page Public Metadata Access' feature. Refer to https://developers.facebook.com/docs/apps/review/login-permissions#manage-pages, https://developers.facebook.com/docs/apps/review/feature#reference-PAGES_ACCESS and https://developers.facebook.com/docs/apps/review/feature#page-public-metadata-access for details. (code 10, subcode null) 'null - null'
	at com.restfb.exception.generator.DefaultFacebookExceptionGenerator$DefaultGraphFacebookExceptionMapper.exceptionForTypeAndMessage(DefaultFacebookExceptionGenerator.java:181)
	at com.restfb.exception.generator.DefaultFacebookExceptionGenerator.throwFacebookResponseStatusExceptionIfNecessary(DefaultFacebookExceptionGenerator.java:65)
	at com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:822)
	at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:739)
	at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:701)
	at com.restfb.DefaultFacebookClient.fetchObject(DefaultFacebookClient.java:293)
	at main.SocialMediaSearch.main(SocialMediaSearch.java:14)
```
I have literally every permission enabled.

**Comment by nbartels** [comment]
I don't think you have the features enabled, because you can only get them if Facebook allows this. 
How does your use case look like. You fetch the data from a different user, or is this your account?

**Comment by MrFirekiller** [comment]
I would fetch data from another user, ie, publicly available stuff like their name, bio, etc.

**Comment by nbartels** [comment]
As short addendum for other users: Check the [Facebook Graph API Explorer](https://developers.facebook.com/tools/explorer/) first. If you get the request running there you can translate it to RestFB very easily and create your code around it afterwards.
