### ISSUE TITLE
Connection Cursor v1.9.0 broken

### ISSUE THREAD

**Issue by slumx** [restfb/restfb#214]
After updating to version 1.9.0 paging /me/groups doesn't work anymore and returns an error 2500 from Facebook (Access-token error).

The problem seems to be that when the end of the response looks like:
```
  "paging": {
    "cursors": {
      "before": "NTQ3OTg5OTk4Ng==",
      "after": "ODI4NDI2NDEyNA=="
    }
  }
```
the next request url becomes: .../me/groups?after=ODI4NDI2NDEyNA...
***The access_token is not copied to the new request***

**Comment by naneunga** [comment]
I have the same issue when paginating through comments.

**Comment by nbartels** [comment]
@slumx how did you paginate ```me/groups``` before 1.9.0? I think this shouldn't be possible because of the missing cursor support ...

Anyway, thanks for the ```access_token``` input.

**Comment by slumx** [comment]
When there is more data you also get a next url. This has always worked with restfb

```
  "paging": {
    "cursors": {
      "before": "NTQ3OTg5OTk4Ng==", 
      "after": "NjQxODAzNDc5MTg5OTU2"
    }, 
    "next": "https://graph.facebook.com/v2.3/810638903/groups?pretty=0&limit=2&after=NjQxODAzNDc5MTg5OTU2"
  }
```

**Comment by nbartels** [comment]
So, I tried to reproduce the issue and wrote a little integration test:

```java
public class FetchMeGroupITCase extends RestFbIntegrationTestBase {
    
    @Test
    public void fetchConnection() {
	DefaultFacebookClient client = new DefaultFacebookClient(getTestSettings().getUserAccessToken(), Version.VERSION_2_3);
	Connection<Group> connection = client.fetchConnection("/me/groups", Group.class, Parameter.with("limit", 3));
	for (List<Group> groupList : connection) {
	    System.out.println("next connection");
	    for (Group group : groupList) {
		System.out.println(group.getName());
	    }
	}
    }
}
```

With the ```limit``` parameter, I can force the connection to be very small, so the next connection object is fetch from facebook very soon. And btw I'm not a member of that many groups :smile: 

I have 5 groups, so I can see the *next connection* String 3 times. 
> 3 groups + 2 groups + 0 groups.

Can you please check your implementation if you do something different?

ATM, I'm a bit confused why this is not working on your side.

**Comment by slumx** [comment]
The only thing different is that I was using v1.0 of the FB API. I will try your test against both API versions when I get back to work Tuesday. 
How does the debug output look? I noticed when the last call was made, which returns 0 results, the request url was different than the previous ones

**Comment by nbartels** [comment]
These are the 3 calls, that are made against the Graph API. Obviously the ```me``` is replaced by the user_id.

I replaced ```access token``` and ```user id```.

```
https://graph.facebook.com/v2.3/me/groups?limit=3&access_token=<acc_token>&format=json
https://graph.facebook.com/v2.3/<user_id>/groups?access_token=<acc_token>&limit=3&after=MTQ2Nzk3OTIyMDMwMzk3
https://graph.facebook.com/v2.3/<user_id>/groups?access_token=<acc_token>&limit=3&after=NTYxNjQ0ODU3MTgzODA0
```

**Comment by slumx** [comment]
Ok that is interesting. My first requests looked exactly like that but the last one was only:

https://graph.facebook.com/v1.0/<user_id>/groups?after=NTYxNjQ0ODU3MTgzODA0

**Comment by slumx** [comment]
I have investigated further. Everything works as expected with restfb v1.8.0. With version 1.9.0 I get some weird results.
- When running
```
FacebookClient fbc = new DefaultFacebookClient(accesstoken, Version.VERSION_2_2);
		
Connection<Group> groupCon = fbc.fetchConnection("/me/groups", Group.class);
for (List<Group> groups : groupCon) {
	for (Group group : groups) {
		System.out.println(group.getName());
	}
}
```
I get the following as the last call which results in an exception 

```
apr. 09, 2015 9:58:25 AM com.restfb.DefaultWebRequestor execute
FINE: Making a GET request to https://graph.facebook.com/v2.2/me/groups?after=ODI4NDI2NDEyNA==
apr. 09, 2015 9:58:25 AM com.restfb.DefaultWebRequestor execute
FINE: Facebook responded with HTTP status code 400 and response body: {"error":{"message":"An active access token must be used to query information about the current user.","type":"OAuthException","code":2500}}
Exception in thread "main" com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: An active access token must be used to query information about the current user. (code 2500, subcode null)
	at com.restfb.DefaultFacebookClient$DefaultGraphFacebookExceptionMapper.exceptionForTypeAndMessage(DefaultFacebookClient.java:1189)
	at com.restfb.DefaultFacebookClient.throwFacebookResponseStatusExceptionIfNecessary(DefaultFacebookClient.java:1104)
	at com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:1038)
	at com.restfb.DefaultFacebookClient.fetchConnectionPage(DefaultFacebookClient.java:397)
	at com.restfb.Connection.fetchNextPage(Connection.java:216)
	at com.restfb.Connection$ConnectionIterator.next(Connection.java:112)
	at com.restfb.Connection$ConnectionIterator.next(Connection.java:71)
	at dk.digitalfootprints.xdev.test.FacebookRestTest.main(FacebookRestTest.java:32)
```
- When I try to use the limit parameter as you did in your test I get an infinite loop, where the value for the before and after cursors are the same.
```
Connection<Group> groupCon = fbc.fetchConnection("/me/groups", Group.class, Parameter.with("limit", "2"));
```
and excerpt from the infinite loops looks like this:

```
apr. 09, 2015 10:06:11 AM com.restfb.DefaultWebRequestor execute
FINE: Making a GET request to https://graph.facebook.com/v2.2/<USER-ID>/groups?access_token=<TOKEN>&limit=2&after=NTE2NzY1MjE1NTk%3D
apr. 09, 2015 10:06:11 AM com.restfb.DefaultWebRequestor execute
FINE: Facebook responded with HTTP status code 200 and response body: {"data":[{"name":"Rostockmusic","id":"8284264124","administrator":true,"bookmark_order":1,"unread":2}],"paging":{"cursors":{"before":"ODI4NDI2NDEyNA==","after":"ODI4NDI2NDEyNA=="},"previous":"https:\/\/graph.facebook.com\/v2.2\/<USER-ID>\/groups?access_token=<TOKEN>&limit=2&before=ODI4NDI2NDEyNA\u00253D\u00253D"}}

apr. 09, 2015 10:06:11 AM com.restfb.DefaultWebRequestor execute
FINE: Making a GET request to https://graph.facebook.com/v2.2/<USER-ID>/groups?access_token=<TOKEN>&limit=2&after=NTE2NzY1MjE1NTk%3D
apr. 09, 2015 10:06:12 AM com.restfb.DefaultWebRequestor execute
FINE: Facebook responded with HTTP status code 200 and response body: {"data":[{"name":"Rostockmusic","id":"8284264124","administrator":true,"bookmark_order":1,"unread":2}],"paging":{"cursors":{"before":"ODI4NDI2NDEyNA==","after":"ODI4NDI2NDEyNA=="},"previous":"https:\/\/graph.facebook.com\/v2.2\/<USER-ID>\/groups?access_token=<TOKEN>&limit=2&before=ODI4NDI2NDEyNA\u00253D\u00253D"}}

apr. 09, 2015 10:06:12 AM com.restfb.DefaultWebRequestor execute
FINE: Making a GET request to https://graph.facebook.com/v2.2/<USER-ID>/groups?access_token=<TOKEN>&limit=2&after=NTE2NzY1MjE1NTk%3D
apr. 09, 2015 10:06:12 AM com.restfb.DefaultWebRequestor execute
FINE: Facebook responded with HTTP status code 200 and response body: {"data":[{"name":"Rostockmusic","id":"8284264124","administrator":true,"bookmark_order":1,"unread":2}],"paging":{"cursors":{"before":"ODI4NDI2NDEyNA==","after":"ODI4NDI2NDEyNA=="},"previous":"https:\/\/graph.facebook.com\/v2.2\/<USER-ID>\/groups?access_token=<TOKEN>&limit=2&before=ODI4NDI2NDEyNA\u00253D\u00253D"}}

apr. 09, 2015 10:06:12 AM com.restfb.DefaultWebRequestor execute
FINE: Making a GET request to https://graph.facebook.com/v2.2/<USER-ID>/groups?access_token=<TOKEN>&limit=2&after=NTE2NzY1MjE1NTk%3D
apr. 09, 2015 10:06:12 AM com.restfb.DefaultWebRequestor execute
FINE: Facebook responded with HTTP status code 200 and response body: {"data":[{"name":"Rostockmusic","id":"8284264124","administrator":true,"bookmark_order":1,"unread":2}],"paging":{"cursors":{"before":"ODI4NDI2NDEyNA==","after":"ODI4NDI2NDEyNA=="},"previous":"https:\/\/graph.facebook.com\/v2.2\/<USER-ID>\/groups?access_token=<TOKEN>&limit=2&before=ODI4NDI2NDEyNA\u00253D\u00253D"}}

apr. 09, 2015 10:06:12 AM com.restfb.DefaultWebRequestor execute
FINE: Making a GET request to https://graph.facebook.com/v2.2/<USER-ID>/groups?access_token=<TOKEN>&limit=2&after=NTE2NzY1MjE1NTk%3D
apr. 09, 2015 10:06:12 AM com.restfb.DefaultWebRequestor execute
FINE: Facebook responded with HTTP status code 200 and response body: {"data":[{"name":"Rostockmusic","id":"8284264124","administrator":true,"bookmark_order":1,"unread":2}],"paging":{"cursors":{"before":"ODI4NDI2NDEyNA==","after":"ODI4NDI2NDEyNA=="},"previous":"https:\/\/graph.facebook.com\/v2.2\/<USER-ID>\/groups?access_token=<TOKEN>&limit=2&before=ODI4NDI2NDEyNA\u00253D\u00253D"}}

```

I'm a part of 21 groups so if i change the limit parameter to 3, so we will have a division with no remainder (21/3 = 7 resultsets) everything works fine :-)

```
Connection<Group> groupCon = fbc.fetchConnection("/me/groups", Group.class, Parameter.with("limit", "3"));
```

**Comment by nbartels** [comment]
This is really strange... 

Do you use maven or the jar from the website?

**Comment by slumx** [comment]
I use maven

**Comment by nbartels** [comment]
Okay, I get the missing access token exception as soon as I use no limit or a limit that's greater or equals than the current group count.

If I use a limit that's less than the count of group objects, everything's fine. I don't see the endless loop. Thanks for your help.

**Comment by slumx** [comment]
Glad to help. I will run my tests again when the new version comes out :-)

**Comment by slumx** [comment]
I just tested with my code again and everything works fine now :-)

**Comment by nbartels** [comment]
:+1:
