### ISSUE TITLE
Cannot fetch Objects

### ISSUE THREAD

**Issue by JSafaiyeh** [restfb/restfb#240]
Trying to fetch objects causes this error:

com.restfb.exception.FacebookNetworkException: A network error occurred while trying to communicate with Facebook: Facebook request failed (HTTP status code null)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: com.restfb.exception.FacebookNetworkException: A network error occurred while trying to communicate with Facebook: Facebook request failed (HTTP status code null)
            at com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:1029)
            at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:958)
            at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:921)
            at com.restfb.DefaultFacebookClient.fetchConnection(DefaultFacebookClient.java:378)
            at com.jsafaiyeh.omni.FeedActivity.onCreate(FeedActivity.java:54)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: android.os.NetworkOnMainThreadException
            at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
            at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:749)
            at com.android.okio.Okio$1.write(Okio.java:70)
            at com.android.okio.RealBufferedSink.flush(RealBufferedSink.java:154)
            at com.android.okhttp.internal.http.HttpConnection.flush(HttpConnection.java:130)
            at com.android.okhttp.internal.http.HttpTransport.flushRequest(HttpTransport.java:73)
            at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:626)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:500)
            at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
            at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
            at com.restfb.DefaultWebRequestor.fetchResponse(DefaultWebRequestor.java:375)
            at com.restfb.DefaultWebRequestor.execute(DefaultWebRequestor.java:361)
            at com.restfb.DefaultWebRequestor.executeGet(DefaultWebRequestor.java:93)
            at com.restfb.DefaultFacebookClient$3.makeRequest(DefaultFacebookClient.java:971)
            at com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:1023)
            at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:958)
            at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:921)
            at com.restfb.DefaultFacebookClient.fetchConnection(DefaultFacebookClient.java:378)
            at com.jsafaiyeh.omni.FeedActivity.onCreate(FeedActivity.java:54)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by nbartels** [comment]
I'm not the Android guy, but I think open http requests in the main thread is not allowed in Android. You have to fetch the Facebook objects in a separate thread. Perhaps the application is not slowed down because of a slow network connection.

**Comment by nbartels** [comment]
Here's a link regarding that topic, so I think this is not a RestfB issue. I close this as a question.

http://stackoverflow.com/questions/6343166/android-os-networkonmainthreadexception
