### ISSUE TITLE
Video upload with restfb libray is not working

### ISSUE THREAD

**Issue by gyansagar** [restfb/restfb#242]
I am getting following error when trying to upload a small .mp4 (2-3 MB in size) video using restfb library:-

Exception in thread "main" com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: (#352) Sorry, the video file you selected is in a format that we don't support. (code 352, subcode null)
	at com.restfb.DefaultFacebookClient$DefaultGraphFacebookExceptionMapper.exceptionForTypeAndMessage(DefaultFacebookClient.java:1219)
	at com.restfb.DefaultFacebookClient.throwFacebookResponseStatusExceptionIfNecessary(DefaultFacebookClient.java:1134)
	at com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:1067)
	at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:978)
	at com.restfb.DefaultFacebookClient.publish(DefaultFacebookClient.java:470)
	at com.restfb.DefaultFacebookClient.publish(DefaultFacebookClient.java:486)

**Comment by gyansagar** [comment]
It was working fine when I checked a few week back.

**Comment by gyansagar** [comment]
file name for video was not in correct format.
