### ISSUE TITLE
Error when fetching URL

### ISSUE THREAD

**Issue by rackom** [restfb/restfb#279]
I was trying to fetch comments that are added via Facebook Social Plugin to web page specified by URL. It seems that there is no other way I can do this but fetching Url object and get webpage ID from it and then make second request to that particular objectID to fetch comments. There is a problem with requests like this:

```java
Url cmmts = client.fetchObject("/?id=" + URLEncoder.encode("http://www.teraz.sk/slovensko/policajne-kontroly-doprava-rychlost/147523-clanok.html", "UTF-8"), Url.class);
```

DefaultFacebookClient will create request with two '?' signs like this:
```
https://graph.facebook.com/v2.4/?id=http%3A%2F%2Fwww.teraz.sk%2Fslovensko%2Fpolicajne-kontroly-doprava-rychlost%2F147523-clanok.html?access_token=1508954452652756%7Cf0tY4wFL1vLKN6aXr-DIcRNWFFs&format=json
```
 so request is not valid and it will end with this error:

```
Exception in thread "main" com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: An access token is required to request this resource. (code 104, subcode null)
	at com.restfb.DefaultFacebookClient$DefaultGraphFacebookExceptionMapper.exceptionForTypeAndMessage(DefaultFacebookClient.java:1238)
	at com.restfb.DefaultFacebookClient.throwFacebookResponseStatusExceptionIfNecessary(DefaultFacebookClient.java:1153)
	at com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:1086)
	at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:997)
	at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:959)
	at com.restfb.DefaultFacebookClient.fetchObject(DefaultFacebookClient.java:419)
	at eu.cogniware.Main.main(Main.java:22)
```

Exact code location where error occurs is line 547 in DefaultFacebookClient.java

```java
protected String makeRequest(String var1, final boolean var2, final boolean var3, final List<BinaryAttachment> var4, Parameter... var5) {
...
        return this.makeRequestAndProcessResponse(new DefaultFacebookClient.Requestor() {
            public Response makeRequest() throws IOException {
                return var3 && !DefaultFacebookClient.this.isHttpDeleteFallback()?DefaultFacebookClient.this.webRequestor.executeDelete(var6 + "?" + var7):(var2?DefaultFacebookClient.this.webRequestor.executePost(var6, var7, var4 == null?null:(BinaryAttachment[])var4.toArray(new BinaryAttachment[var4.size()])):DefaultFacebookClient.this.webRequestor.executeGet(var6 + "?" + var7));
...
}
```

**Comment by nbartels** [comment]
Please try this code: 

```java
FacebookClient client = new DefaultFacebookClient(accessToken, Version.VERSION_2_4);
Parameter urlParam = Parameter.with("id", 
     "http://www.teraz.sk/slovensko/policajne-kontroly-doprava-rychlost/147523-clanok.html");
Url cmmts = client.fetchObject("/", Url.class, urlParam);
``` 

The variable `urlParam` is only used for readability.

**Comment by rackom** [comment]
Ok thank you, it seems to be working.
