### ISSUE TITLE
Facebook OauthException title required version 2.5?

### ISSUE THREAD

**Issue by NickEckert** [restfb/restfb#297]

**Comment by NickEckert** [comment]
Here's the stack trace:
```java
ERROR [2015-09-19 23:22:06,141] com.sanction.lightning.resources.FacebookResource: Bad Facebook OAuth token for username Nick
! com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: (#12) title requires version v2.5 or higher (code 12, subcode null)
! at com.restfb.DefaultFacebookClient$DefaultGraphFacebookExceptionMapper.exceptionForTypeAndMessage(DefaultFacebookClient.java:1238) ~[restfb-1.14.1.jar:na]
! at com.restfb.DefaultFacebookClient.throwFacebookResponseStatusExceptionIfNecessary(DefaultFacebookClient.java:1153) ~[restfb-1.14.1.jar:na]
! at com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:1086) ~[restfb-1.14.1.jar:na]
! at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:997) ~[restfb-1.14.1.jar:na]
! at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:959) ~[restfb-1.14.1.jar:na]
! at com.restfb.DefaultFacebookClient.fetchObject(DefaultFacebookClient.java:419) ~[restfb-1.14.1.jar:na]
```
Here is the code:
```java
public List<String> getFacebookUserVideos() {
    JsonObject videos = client.fetchObject("me/videos", JsonObject.class,
            Parameter.with("type","uploaded"), Parameter.with("fields","id, title"));
    JsonArray videoArray = videos.getJsonArray("data");

    List<String> urlList = Lists.newArrayList();
    for (int i = 0; i < videos.length() - 1; i++) {
      urlList.add(videoArray.getJsonObject(i).toString());
    }

    return urlList;
  }
```
client is the `DefaultFacebookClient()`

**Comment by nbartels** [comment]
It's the `title` in your request. Try it `Parameter.with("fields","id")` and it should work. At least that's what the exception says. 

Interesting fact: 2.4 is the latest released version. Perhaps Facebook is preparing something ...

**Comment by nbartels** [comment]
Is your problem solved?

**Comment by NickEckert** [comment]
Yes, I put a tag that doesn't exist for photos, thank you.
