### ISSUE TITLE
AdCreativeLinkDataCallToAction value cannot be deserialized

### ISSUE THREAD

**Issue by hkroger** [restfb/restfb#507]
AdCreativeLinkDataCallToAction has a field "value" and there seems to be a problem when deserializing that:

    Caused by: com.restfb.exception.FacebookJsonMappingException: Don't know how to map JSON to class java.lang.Object. Are you sure you're mapping to the right class? Offending JSON is '{"link":"http://www.mycompany.com/"}'.
	at com.restfb.DefaultJsonMapper.toPrimitiveJavaType(DefaultJsonMapper.java:620) ~[restfb-1.26.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:238) ~[restfb-1.26.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaType(DefaultJsonMapper.java:738) ~[restfb-1.26.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:299) ~[restfb-1.26.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaType(DefaultJsonMapper.java:738) ~[restfb-1.26.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:299) ~[restfb-1.26.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaType(DefaultJsonMapper.java:738) ~[restfb-1.26.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:299) ~[restfb-1.26.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaType(DefaultJsonMapper.java:738) ~[restfb-1.26.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:299) ~[restfb-1.26.0.jar:?]
	at com.restfb.Connection.<init>(Connection.java:157) ~[restfb-1.26.0.jar:?]
	at com.restfb.DefaultFacebookClient.fetchConnection(DefaultFacebookClient.java:356) ~[restfb-1.26.0.jar:?]

If I leave out `object_story_spec` from the fields to be loaded, `AdCreative` can be loaded fine.

**Comment by hkroger** [comment]
{
           "object_type" : "INVALID",
           "object_story_id" : "123_234",
           "name" : "some text",
           "thumbnail_url" : "https://www.abc.com/",
           "run_status" : "ACTIVE",
           "object_story_spec" : {
              "page_id" : "123",
              "link_data" : {
                 "link" : "http://www.mycompany.com/",
                 "child_attachments" : [
                    {
                       "name" : "Some text",
                       "call_to_action" : {
                          "type" : "LEARN_MORE"
                       },
                       "link" : "http://www.mycompany.com/",
                       "picture" : "http://pic.test.com/1"
                    },
                    {
                       "link" : "http://www.mycompany.com/",
                       "call_to_action" : {
                          "type" : "LEARN_MORE"
                       }
                    },
                    {
                       "link" : "http://www.mycompany.com/",
                       "call_to_action" : {
                          "type" : "LEARN_MORE"
                       }
                    }
                 ],
                 "multi_share_optimized" : true,
                 "multi_share_end_card" : true,
                 "call_to_action" : {
                    "type" : "LEARN_MORE",
                    "value" : {
                       "link" : "http://www.mycompany.com/"
                    }
                 },
                 "message" : "Some text"
              }
           },
           "id" : "456"
        }
