### ISSUE TITLE
AdsImageCrops deserialization doesn't work

### ISSUE THREAD

**Issue by hkroger** [restfb/restfb#523]
Hi,

I have an issue with deserializing AdsImageCrops objects in AdCreatives. The offending JSON is:

    "image_crops": {
        "100x100": [[27,0],[655,628]]
    },

That JsonArray approach doesn't work in generic fashion. It breaks up everything there is an element because the JSON deserializer cannot deserialize to Object. I don't know what the fix could be though...

**Comment by hkroger** [comment]
```
Caused by: com.restfb.exception.FacebookJsonMappingException: JSON is an array but is being mapped as an object - you should map it as a List instead. Offending JSON is '[27,0]'.
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:212) ~[restfb-1.28.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaList(DefaultJsonMapper.java:175) ~[restfb-1.28.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaType(DefaultJsonMapper.java:707) ~[restfb-1.28.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:300) ~[restfb-1.28.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaType(DefaultJsonMapper.java:743) ~[restfb-1.28.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:300) ~[restfb-1.28.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaList(DefaultJsonMapper.java:175) ~[restfb-1.28.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaType(DefaultJsonMapper.java:707) ~[restfb-1.28.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:300) ~[restfb-1.28.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaType(DefaultJsonMapper.java:743) ~[restfb-1.28.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:300) ~[restfb-1.28.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaType(DefaultJsonMapper.java:743) ~[restfb-1.28.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:300) ~[restfb-1.28.0.jar:?]
	at com.restfb.Connection.<init>(Connection.java:157) ~[restfb-1.28.0.jar:?]
	at com.restfb.DefaultFacebookClient.fetchConnectionPage(DefaultFacebookClient.java:382) ~[restfb-1.28.0.jar:?]
	at com.restfb.Connection.fetchNextPage(Connection.java:201) ~[restfb-1.28.0.jar:?]
	at com.restfb.Connection$ConnectionIterator.next(Connection.java:109) ~[restfb-1.28.0.jar:?]
	at com.restfb.Connection$ConnectionIterator.next(Connection.java:70) ~[restfb-1.28.0.jar:?]
```
