### ISSUE TITLE
Issue with Targeting rule deserialization

### ISSUE THREAD

**Issue by hkroger** [restfb/restfb#535]
Trying to deserialize adset targeting rule gives an exception. The targeting is like this:
```
{
    "id": "123123123",
    "targeting": {
        "age_max": 65,
        "age_min": 64,
        "genders": [
            2
        ],
        "geo_locations": {
            "countries": [
                "AO"
            ],
            "location_types": [
                "home"
            ]
        },
        "page_types": [
            "desktopfeed",
            "mobilefeed"
        ],
        "product_audience_specs": [
            {
                "exclusions": [
                    {
                        "retention_seconds": "604800",
                        "rule": "{\"event\":{\"eq\":\"BOUGHT\"}}"
                    }
                ],
                "inclusions": [
                    {
                        "retention_seconds": "2592000",
                        "rule": "{\"event\":{\"eq\":\"VIEWED\"}}"
                    }
                ],
                "product_set_id": "234234234234"
            }
        ]
    }
}
```

Error is like this: `com.restfb.exception.FacebookJsonMappingException: Unable to map JSON to Java. Offending JSON is '{"rule":"{\"event\":{\"eq\":\"BOUGHT\"}}","retention_seconds":"604800"}'.`

And stack trace: 

```
Caused by: java.lang.ClassCastException: com.restfb.types.ads.RuleData cannot be cast to com.restfb.types.ads.RuleOp
	at com.restfb.types.ads.RuleFactory.createRuleData(RuleFactory.java:180) ~[restfb-1.29.0.jar:?]
	at com.restfb.types.ads.RuleFactory.createRuleFromJson(RuleFactory.java:105) ~[restfb-1.29.0.jar:?]
	at com.restfb.types.ads.TargetingProductAudienceSubSpec.convertRule(TargetingProductAudienceSubSpec.java:47) ~[restfb-1.29.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
	at com.restfb.DefaultJsonMapper.invokeJsonMappingCompletedMethods(DefaultJsonMapper.java:345) ~[restfb-1.29.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:311) ~[restfb-1.29.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaList(DefaultJsonMapper.java:175) ~[restfb-1.29.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaType(DefaultJsonMapper.java:707) ~[restfb-1.29.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:300) ~[restfb-1.29.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaList(DefaultJsonMapper.java:175) ~[restfb-1.29.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaType(DefaultJsonMapper.java:707) ~[restfb-1.29.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:300) ~[restfb-1.29.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaType(DefaultJsonMapper.java:743) ~[restfb-1.29.0.jar:?]
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:300) ~[restfb-1.29.0.jar:?]
```

**Comment by nbartels** [comment]
Ah, that's really interesting. The "rule" field is provided as String and not as JsonObject. So we have to implement a fallback solution for this special case ...

**Comment by hkroger** [comment]
It really is interesting. Although the rule is created with rule being a json structure instead of string with json content, somehow the rule ends up being a string with json content when querying...

**Comment by nbartels** [comment]
I checked this already yesterday and think I can fix it this evening. But I have to check the docs - perhaps this is a bug on Facebook side?

**Comment by hkroger** [comment]
It might be a bug but I'm afraid that they cannot just fix it and break the API so we have to live with it until next versions of the API...
