### ISSUE TITLE
The URL couldn't be validated. Callback verification failed with the following errors: HTTP Status Code = 503; HTTP Message = Service Unavailable

### ISSUE THREAD

**Issue by karenworld** [restfb/restfb#929]
I got a HTTP Status Code = 503 and the heroku log reveals 
 Caused by: java.lang.NoClassDefFoundError: com/restfb/FacebookClient
2018-11-01T03:05:28.605926+00:00 app[web.1]: at java.lang.Class.getDeclaredFields0(Native Method)
2018-11-01T03:05:28.605928+00:00 app[web.1]: at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
2018-11-01T03:05:28.605929+00:00 app[web.1]: at java.lang.Class.getDeclaredFields(Class.java:1916)
2018-11-01T03:05:28.605931+00:00 app[web.1]: at org.apache.catalina.util.Introspection.getDeclaredFields(Introspection.java:110)
2018-11-01T03:05:28.605933+00:00 app[web.1]: at org.apache.catalina.startup.WebAnnotationSet.loadFieldsAnnotation(WebAnnotationSet.java:269)
2018-11-01T03:05:28.605934+00:00 app[web.1]: at org.apache.catalina.startup.WebAnnotationSet.loadApplicationServletAnnotations(WebAnnotationSet.java:137)
2018-11-01T03:05:28.605936+00:00 app[web.1]: at org.apache.catalina.startup.WebAnnotationSet.loadApplicationAnnotations(WebAnnotationSet.java:69)
2018-11-01T03:05:28.605937+00:00 app[web.1]: at org.apache.catalina.startup.ContextConfig.applicationAnnotationsConfig(ContextConfig.java:328)
2018-11-01T03:05:28.605939+00:00 app[web.1]: at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:768)
2018-11-01T03:05:28.605940+00:00 app[web.1]: at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
2018-11-01T03:05:28.605942+00:00 app[web.1]: at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
2018-11-01T03:05:28.605943+00:00 app[web.1]: at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5154)
2018-11-01T03:05:28.605945+00:00 app[web.1]: at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
2018-11-01T03:05:28.605946+00:00 app[web.1]: ... 6 more 

Is FacebookClient deprecated or ?

**Comment by nbartels** [comment]
No, `FacebookClient` is still there. It's the interface for the `DefaultFacebookClient`. Are you sure the jar is in your project? 
Maybe you have this problem: https://stackoverflow.com/questions/20965256/tomcat-7-server-wont-load-class-classnotfoundexception

**Comment by karenworld** [comment]
Hello nbartels,

I have read the stackoverflow's solution which I have added in the library to the build path via deployment Assembly before exported it as war and then re-deployed to Heroku.

But, it is still giving me the same error.

In my lib folder which I have included in the work path I have javax-servlet-api-3.1 and restfb.jar

What do you think I am missing ?

Do I have to embed tomcat inside as well ?

**Comment by nbartels** [comment]
Sorry, I never used heroku. But according to the exception, the class file is still missing and this can only happen if the class path is wrong or the jar is missing completely.

**Comment by karenworld** [comment]
But, I examined my war file and it shows the class file and the jar is all there.

 5257 Sat Nov 03 16:07:32 SGT 2018 WEB-INF/classes/FBChat.class
     0 Wed Oct 31 21:52:46 SGT 2018 WEB-INF/lib/
 85353 Wed Oct 31 21:58:02 SGT 2018 javax.servlet-api-3.0.1.jar
635195 Wed Oct 31 21:56:40 SGT 2018 restfb-2.12.0.jar
 41203 Sat Nov 03 15:53:50 SGT 2018 slf4j-api-1.7.25.jar

**Comment by nbartels** [comment]
I checked the heroku documentation and perhaps this is helpful:
https://devcenter.heroku.com/articles/deploying-java

Obviously the maven pom needs a special dependency to get the jars into heroku. And they don't work with a plain war. But this is just an idea I get using google ;).

So you need some heroku guy to solve this. The restfb jar has all classes inside :)
