### ISSUE TITLE
Unicode characters results in ParseException

### ISSUE THREAD

**Issue by krzyk** [restfb/restfb#943]
Example code:
```
            return new DefaultFacebookClient(
                token,
                new DefaultWebRequestor() {
                    @Override
                    public Response executeGet(final String url) {
                        return new Response(
                            HttpURLConnection.HTTP_OK,
                            "{\"id\":\"b4TUmsLXoK\",\"name\":\"ⲉ鯨ɯ摓㻦恛҉祐\f፲\"}"
                        );
                    }
                }``,
                new DefaultJsonMapper(),
                Version.LATEST
            ).fetchObject(
                "me", User.class
            );
```

Results in exception:
```
Caused by: com.restfb.exception.FacebookJsonMappingException: Unable to map JSON to Java. Offending JSON is '{"id":"b4TUmsLXoK","name":"ⲉ鯨ɯ摓㻦恛҉祐፲"}'.
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:250)
	at com.restfb.DefaultFacebookClient.fetchObject(DefaultFacebookClient.java:310)
	at org.takes.facets.auth.social.PsFacebook.fetch(PsFacebook.java:193)
	... 24 more
Caused by: com.restfb.json.ParseException: Expected valid string character at 1:35
	at com.restfb.json.JsonParser.error(JsonParser.java:370)
	at com.restfb.json.JsonParser.expected(JsonParser.java:363)
	at com.restfb.json.JsonParser.readStringInternal(JsonParser.java:199)
	at com.restfb.json.JsonParser.readString(JsonParser.java:187)
	at com.restfb.json.JsonParser.readValue(JsonParser.java:84)
	at com.restfb.json.JsonParser.readObject(JsonParser.java:139)
	at com.restfb.json.JsonParser.readValue(JsonParser.java:88)
	at com.restfb.json.JsonParser.parse(JsonParser.java:67)
	at com.restfb.json.Json.parse(Json.java:295)
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:198)
	... 26 more
```

But any UTF-8 character is a correct json character so it should be handled.

**Comment by nbartels** [comment]
Thanks for your example. The problem is, that your JSON is not valid. 

here is your code with the fixed JSON:

```java
            return new DefaultFacebookClient(
                token,
                new DefaultWebRequestor() {
                    @Override
                    public Response executeGet(final String url) {
                        return new Response(
                            HttpURLConnection.HTTP_OK,
                            "{\"id\":\"b4TUmsLXoK\",\"name\":\"ⲉ鯨ɯ摓㻦恛҉祐\\f፲\"}"
                        );
                    }
                }``,
                new DefaultJsonMapper(),
                Version.LATEST
            ).fetchObject(
                "me", User.class
            );
```
There was a `\` missing in the name. You have to escape the character and then it is `\\`.
I create additionally to your test a JSON file without the escaped quotes and it worked directly, so the parser is correct 😄 

Here is the code for my unittest:
```java 
  @Test
  public void unicodeGet() {
    User user = createJsonMapper().toJavaObject(jsonFromClasspath("api/unicode"), User.class);
    assertThat(user).isNotNull();

    User user2 = new DefaultFacebookClient("blub", new DefaultWebRequestor() {
      @Override
      public Response executeGet(final String url) {
        return new Response(HttpURLConnection.HTTP_OK, "{\"id\":\"b4TUmsLXoK\",\"name\":\"ⲉ鯨ɯ摓㻦恛҉祐\\f፲\"}");
      }
    }, new DefaultJsonMapper(), Version.LATEST).fetchObject("me", User.class);
    assertThat(user2).isNotNull();
  }
```

**Comment by krzyk** [comment]
Yeah, you are right, I copy pasted wrong character there, thanks for the info :)
