### ISSUE TITLE
Getting offending JSON exception when deserialising to WebhookObject class

### ISSUE THREAD

**Issue by RedEagle** [restfb/restfb#951]
One of my Java bot applications got the following JSON object in the webhook API service:

`{
  "object": "page",
  "entry": [
    {
      "id": "692521420913831",
      "time": 1546532206632,
      "messaging": [
        {
          "sender": {
            "id": "1886939548028072"
          },
          "recipient": {
            "id": "692521420913831"
          },
          "timestamp": 1546532206372,
          "message": {
            "mid": "t8Z18hGWisXFy90yYBRHwnOwRWDDf7jJyJdxFrmLryLNJTyS7eBGQOrzuKbVtlDqlYf7WgtMkgshUzwUfznHcg",
            "seq": 177139,
            "text": "For security reasons this isn't the actual text the chatbot application received. Nontheless I counted the chars and it had more than 1024 chars like the error states.",
            "nlp": {
              "errors": [
                {
                  "code": "msg-invalid",
                  "message": "Message is either too short or too long (max is 1024)"
                }
              ]
            }
          }
        }
      ]
    }
  ]
}`

And got the following exception:

`Exception in thread "Thread-419" com.restfb.exception.FacebookJsonMappingException: Unable to map JSON to Java. Offending JSON is '{"errors":[{"code":"msg-invalid","message":"Message is either too short or too long (max is 1024)"}]}'.
2019-01-03 16:16:47,916 ERROR [stderr] (Thread-419)     at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:324)
2019-01-03 16:16:47,916 ERROR [stderr] (Thread-419)     at com.restfb.DefaultJsonMapper.toJavaType(DefaultJsonMapper.java:753)
2019-01-03 16:16:47,916 ERROR [stderr] (Thread-419)     at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:304)
2019-01-03 16:16:47,917 ERROR [stderr] (Thread-419)     at com.restfb.DefaultJsonMapper.toJavaType(DefaultJsonMapper.java:753)
2019-01-03 16:16:47,917 ERROR [stderr] (Thread-419)     at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:304)
2019-01-03 16:16:47,917 ERROR [stderr] (Thread-419)     at com.restfb.DefaultJsonMapper.toJavaList(DefaultJsonMapper.java:176)
2019-01-03 16:16:47,917 ERROR [stderr] (Thread-419)     at com.restfb.DefaultJsonMapper.toJavaType(DefaultJsonMapper.java:717)
2019-01-03 16:16:47,917 ERROR [stderr] (Thread-419)     at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:304)
2019-01-03 16:16:47,917 ERROR [stderr] (Thread-419)     at com.restfb.DefaultJsonMapper.toJavaList(DefaultJsonMapper.java:176)
2019-01-03 16:16:47,917 ERROR [stderr] (Thread-419)     at com.restfb.DefaultJsonMapper.toJavaType(DefaultJsonMapper.java:717)
2019-01-03 16:16:47,917 ERROR [stderr] (Thread-419)     at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:304)`

From the small search that I did, I didn't find any Facebook reference that mentions the possible existance of `errors` object in the first level of `nlp` object. The Facebook documentation I found only mentions that `nlp` object can have `entities` object array.

The problem is that given this JSON deserialization problem, I'm not able to determine the sender's ID, so I'm not able to send a message to the FB user informing him that there was an error or that the message he specified was too long.

I solve this for now, by making my own deserialization using GSON and interpreting `errors` object array.

Will you consider adding `errors` object array to `NlpResult` class for sucessfull serialization?

**Comment by nbartels** [comment]
Many thanks for this JSON. I couldn't find any information in the reference about the error field either. That's the reason why we didn't implement any handling.

It will be added to next RestFB version.
